server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-705454.okta.com/oauth2/default
    client-id: 0oa1cscoxiACCgkJA357
    client-secret: vHmZl_iH2Mq1MqIzIQsm1hYiACawxHEdTgkWF5ZW
spring:
  thymeleaf:
    cache: false